name: Tebex-MCJava
main: net.buycraft.plugin.nukkit.BuycraftPlugin
version: "${project.version}"
author: Tebex
api: [1.0.0, 2.0.0]
commands:
  tebex:
    description: Main command for the Tebex-MCJava plugin.