name: BuycraftX
main: net.buycraft.plugin.nukkit.BuycraftPlugin
version: "${project.version}"
author: Buycraft
api: [1.0.0, 2.0.0]
commands:
  buycraft:
    description: Main command for the Buycraft plugin.