name: Tebex-MCJava
main: net.buycraft.plugin.bukkit.BuycraftPlugin
version: ${project.version}
author: Tebex
softdepend: [ProtocolLib]
commands:
  tebex:
    description: Main command for the Tebex-MCJava plugin.
api-version: 1.13